name: Test Frontend

on:
  push:
    paths:
      - "frontend/*"
      - ".github/workflows/test-frontend.yml"
  pull_request:
    paths:
      - "frontend/*"
      - ".github/workflows/test-frontend.yml"

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
